### ISSUE TITLE
Compilation Error with validify 1.1.1 in axum-valid Project: Cannot Find Attribute 'prost'

### ISSUE THREAD

**Issue by gengteng** [biblius/validify#33]
Hello,

Firstly, I would like to express my appreciation for the validify crate. It has been an essential part of my project, axum-valid, and has greatly aided in its development.

I am currently facing a compilation issue when upgrading from validify version 1.0.12 to 1.1.1. While the project compiles successfully with version 1.0.12, the newer version introduces an error related to the prost attribute. Below is a minimal example that reproduces this issue, along with the error message and some additional context.

# Environment

rustc 1.74.1 (a28077b28 2023-12-04)
binary: rustc
commit-hash: a28077b28a02b92985b3a3faecf92813155f1ea1
commit-date: 2023-12-04
host: aarch64-apple-darwin
release: 1.74.1
LLVM version: 17.0.4

# Steps to Reproduce

Update validify to version 1.1.1 in the axum-valid project.
Use the following code snippet:

```rust
use validify::Validify;

fn main() {
    let mut data = Data {
        v0: 5,
        v1: "abcDEF".into(),
    };
    println!("{data:?}");
    data.validify_self().unwrap();
    println!("{data:?}");
}

#[derive(prost::Message, validify::Validify)]
struct Data {
    #[prost(int32, tag = "1")]
    #[validate(range(min = 5.0, max = 10.0))]
    v0: i32,
    #[prost(string, tag = "2")]
    #[modify(lowercase)]
    #[validate(length(min = 1, max = 10))]
    v1: String,
}

```

Dependencies:
```toml
[dependencies]
prost = "0.12.3"
serde = "1.0.193"
#validify = "=1.0.12"
#validify_derive = "=1.0.12"
validify = "1.1.1"
validify_derive = "1.1.1"
```

# Expected Behavior

The code compiles without any errors, as is the case with validify version 1.0.12.

# Actual Behavior

Compilation fails with the following error:

```
error: cannot find attribute `prost` in this scope
  --> src/main.rs:15:7
   |
15 |     #[prost(int32, tag = "1")]
   |       ^^^^^
   |
   = note: `prost` is in scope, but it is a crate, not an attribute
```

# Additional Context

* The issue seems to be related to changes introduced in validify version 1.1.1.
* To avoid this error, the project currently explicitly sets validify_derive = "=1.0.12".

It seems that the `Validify` derive macro is primarily designed for the serde ecosystem. However, it has also been working well with structs without deriving `Deserialize` trait in my axum-valid library. I would be grateful if you could look into this issue, as it seems that the changes in the `Validify` derive macro in version 1.1.1 might be causing this problem. Any assistance or resolution you could provide would be immensely appreciated.

Thank you very much for your time and support.

**Comment by biblius** [comment]
Hello! Glad you like the crate and thanks for the kind words <3

This issue appears to be related to the change:
`Field level attributes are now propagated to payload fields.`

The error occurs because the generated payload struct does not derive prost's `Message`. Also, because payload fields are `Option`s, even if it would be forwarded the prost annotation that would get forwarded to the payload would not be of the correct type (from my understanding the correct type for `Option`s is `message`, i.e. `prost(message, ...)`), but in this case the prost type would be `string` which does not correspond to `Option<String>`.

This is my main concern about the payload; it is sometimes unnecessary and adds bloat (e.g. when one never uses the actual payload, but still needs modifiers) and it seems to me you are experiencing just that.

Can you share more details on how you are validating the struct? Specifically, are you using the generated payload or the original struct?

The solution to the latter would then be to separate payload generation to another macro altogether, something along the lines of `#[derive(Payload)]`. This would still enable modifiers on the struct, but would not create a payload and would make the example you provided compile.

Since validify was primarily intended to be used for JSON payloads, the protobufs escaped my mind at the time. However given this issue, I am definitely planning on separating the `Validify` and payload generation in the next release. It should then work without any issues.

Thanks for pointing this out!

**Comment by gengteng** [comment]
Hi, @biblius.

Thank you for your response and assistance with my previous issue. I deeply appreciate your time and expertise.

The core logic of axum-valid relies on being able to acquire a Payload type associated with a generic type T. This is essential for constructing an instance of `Json<T>` by first constructing an instance of `Json<T::Payload>` using `FromRequest`. The process involves validating, modifying, and then converting T::Payload back into T, ultimately recombining into Json<T>. This pattern is common in web request handling to ensure data validity and security.

The latest version of validify no longer provides a `Payload` type, impacting our ability to perform the aforementioned logic. To address this, I am attempting to introduce the following trait into validify:

```rust
pub trait Payload {
    type Payload where Self: From<Self::Payload>;
}
```

I believe that by integrating this Payload trait, axum-valid can maintain its functionality, allowing us to effectively handle web requests. I'm currently working on implementing and testing this solution and am hopeful for its success.

I would greatly appreciate any thoughts or suggestions you might have on this approach. I aim to continue using validify and hope to make it work seamlessly with axum-valid. I will promptly inform you of any progress in my implementation. Thank you once again for your previous support, and I look forward to any further collaboration.

Thank you again for your time and support. I eagerly await your valuable input.

**Comment by biblius** [comment]
I've added a `ValidifyPayload` trait to associate payloads to their original structs (1.3.0). I've played around a bit with axum-valid but there's unfortunately no way to make the payload work with `prost`, due to the reasons I've mentioned in my first comment (`prost` attributes that get propagated to the payload do not match the `Option` type). One possible solution to this would be to only propagate certain (user-defined) attributes to the payload. Let me know what you think :)

**Comment by gengteng** [comment]
> I've added a `ValidifyPayload` trait to associate payloads to their original structs (1.3.0). I've played around a bit with axum-valid but there's unfortunately no way to make the payload work with `prost`, due to the reasons I've mentioned in my first comment (`prost` attributes that get propagated to the payload do not match the `Option` type). One possible solution to this would be to only propagate certain (user-defined) attributes to the payload. Let me know what you think :)

Thank you for your reply. The axum-valid introduces two extractors: Validified and ValidifiedByRef. The former only supports construction based on serde deserialization, using the Payload type for construction, validation, and modification to obtain the desired data. The latter directly utilizes deserialization methods like prost and others that are not serde-based (without using payload), performing validation and modification through references. Of course, the latter also supports serde deserialization, but it treats missing field errors as deserialization errors. This design is based on the old version of validify, and I am also hoping to and working on implementing something similar based on the new version.

**Comment by gengteng** [comment]
Thanks for your support. It was a big help for my project upgrade. I'm closing this issue now.
